### PR TITLE
improve deserialization performance

### PR DESCRIPTION
**Pull request by 0x53A**
closes https://github.com/Zaid-Ajaj/Fable.SimpleJson/issues/30

image

### CODE REVIEW

**Comment by 0x53A** [comment]
Is ``TypeInfo`` considered a public API? If yes, then this would be a breaking change.

**Comment by 0x53A** [comment]
No idea why I thought using the Type as key didn't work - it does.

**Comment by 0x53A** [comment]
bah, type equality doesn't work for anonymous records:

```f#
type T1 = {| name: string; child: {| name: string |} |}
type T2 = {| numbers: int list |}


printfn "%O" (typeof<T1> = typeof<T2>)
```

prints ``true``.

[fable repl link](https://fable.io/repl/#?code=LAKFBcE8AcFMAIAqBGeBeeBvAPvAdgIYC2sAXPAM7gBOAlngOYDc8AxgBa0A2AJuTvmJlKNeg3jYAvhMkQYCRACZ0WXHgCuRAEaxqFcvXDwutKjNAWQ0OnnAAzPPABEAUgDyT+AAoocAPZ2ADwoAHwqvrABwYohAJSWQA&html=Q&css=Q)

**Comment by Zaid-Ajaj** [comment]
Awesome work @0x53A :fire: :fire: :fire: 

> Edit: I changed the public api back

Doesn't that affect the performance gains of `lazy`?

Since all tests are passing, let me know if this is ready and I will merge/publish etc. We can fix anonymous records caching when the Fable issue is fixed :smile:

**Comment by 0x53A** [comment]
> Doesn't that affect the performance gains of lazy?

No(t much), there is still a lazy object, and the delayed function just calls lazy.Value.
There might be minimal overhead for the additional function call, but the JS engine can probably inline it.

> Since all tests are passing, let me know if this is ready and I will merge/publish etc.

Ready 👍

**Comment by Zaid-Ajaj** [comment]
> Ready 👍

Done! Will update Remoting.Client later this evening ;)

**Comment by 0x53A** [comment]
I ran ``paket update`` and it's much faster. On a really quick test 13 seconds to 5 seconds!

Thanks!

**Comment by Zaid-Ajaj** [comment]
You did all the heavy lifting :wink: Remoting.Client is now updated as well to v5.5

**Pull request merged**
